---
title: "homework2"
output:
  pdf_document: default
  html_document: default
date: "2023-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(ggpubr)
ddh <- read_csv("homework-2/ddh.csv")
```



```{r cars}
# Sample data

# Sample data


overall_range_twa = range(ddh$glutwa)
overall_range_range = range(ddh$glurange)
overall_range_sd = range(ddh$glusd)

ddh <- ddh%>%
  mutate(delay = if_else(delayed_fn == 0, "IGF", "LGD"))
  

par(mfrow = c(1, 3))
# Create a boxplot stratified by the 'Category' variable

# ggplot(ddh, aes(x = glutwa, fill = delay)) +
#   geom_boxplot(color = "black") +
#   scale_fill_manual(values = c("white", "darkgrey")) +
#   labs(title = "Boxplot of x Stratified by y",
#        x = "Group",
#        y = "Variable x")

a= ggplot(ddh, aes(x = delay, y = glutwa, fill = delay)) + geom_boxplot(outlier.shape = NA, show.legend =  FALSE) + labs(title = "", x ="TWA", y = "") + theme_bw() + scale_y_continuous(trans= 'log2', breaks = c(50,100,200,300,400,500), limits = c(50, 500)) + scale_fill_manual(values = c(IGF = "white", LGD = "darkgray"))

b = ggplot(ddh, aes(x = delay, y = glurange, fill = delay)) + geom_boxplot(outlier.shape = NA, show.legend =  FALSE) + labs(title = "", x ="Range", y = "") + theme_bw() + scale_y_continuous(trans= 'log10', breaks = c(1,10,100,1000), limits = c(1, 1000)) + scale_fill_manual(values = c(IGF = "white", LGD = "darkgray"))

c = ggplot(ddh, aes(x = delay, y = glusd, fill = delay)) + geom_boxplot(outlier.shape = NA, show.legend =  FALSE) + labs(title = "", x ="SD", y = "") + theme_bw() + scale_y_continuous(trans= 'log10', breaks = c(1,10,100,200,300), limits = c(1,300)) + scale_fill_manual(values = c(IGF = "white", LGD = "darkgray"))

# boxplot(glutwa ~ delay, data = ddh, col = c("white", "darkgray"), main = "Boxplot of Glucose TWA", xlab = "TWA", ylab = "", ylim = overall_range_twa, outline = FALSE, width = c(0.5,0.5), frame = FALSE, log ='y') 
# 
# boxplot(glurange ~ delay, data = ddh, col = c("white", "darkgray"), main = "Boxplot of Glucose Range", xlab = "Range", ylab = "", ylim = overall_range_range, outline = FALSE, width = c(0.5,0.5), frame = FALSE, log ='y') 
# 
# boxplot(glusd ~ delay, data = ddh, col = c("white", "darkgray"), main = "Boxplot of Glucose SD", xlab = "SD", ylab = "", outline = FALSE,ylim = overall_range_sd, width = c(0.5,0.5), frame = FALSE, log ="y") 

plot <- ggarrange(a, b, c,
          ncol = 3, nrow = 1)

annotate_figure(plot, top = "Donor glucose measures, mg/dL")
```

```{r}
# model<- glm(
#   delayed_fn ~ glutwa + glurange + glusd,
#   data = ddh,
#   family = "binomial"
# )
# 
# model_adj<- glm(
#   delayed_fn ~ glutwa + glurange + glusd +
#     d_age + d_cod + hemo_instability,
#   data = ddh,
#   family = "binomial"
# )

model_TWA_adj<- glm(
  delayed_fn ~ log2(glutwa) +
    d_age + d_cod + hemo_instability,
  data = ddh,
  family = "binomial"
)

model_TWA<- glm(
  delayed_fn ~ log2(glutwa),
  data = ddh,
  family = "binomial"
)

model_range <- glm(
  delayed_fn ~ log2(glurange),
  data = ddh,
  family = "binomial"
)

model_range_adj <- glm(
  delayed_fn ~ log2(glurange) + 
    d_age + d_cod + hemo_instability,
  data = ddh,
  family = "binomial"
)

model_sd <- glm(
  delayed_fn ~ log2(glusd),
  data = ddh,
  family = "binomial"
)

model_sd_adj <- glm(
  delayed_fn ~ log2(glusd) +
    d_age + d_cod + hemo_instability,
  data = ddh,
  family = "binomial"
)
summary(model_TWA)
summary(model_TWA_adj)
summary(model_range)
summary(model_range_adj)
summary(model_sd)
summary(model_sd_adj)

# summary(model)
# summary(model_adj)

```

```{r}
# Unadjusted TWA
print("Unadjusted TWA")
exp(0.3937)

a = confint(model_TWA, "log2(glutwa)")
exp(a[1])
exp(a[2])

#Adjusted TWA
print("Adjusted TWA")

exp(0.365436)

b = confint(model_TWA_adj, "log2(glutwa)")
exp(b[1])
exp(b[2])

#Unadjusted Range
exp(0.03300)

c = confint(model_range, "log2(glurange)", level = 0.975)
exp(c[1])
exp(c[2])

#Adjusted Range

exp(0.050592)

d = confint(model_range_adj, "log2(glurange)", level = 0.975)
exp(d[1])
exp(d[2])

#Unadjusted SD

exp(0.11106)

e = confint(model_sd, "log2(glusd)", level = 0.975)
exp(e[1])
exp(e[2])

#Adjusted SD

exp(0.118659)

f = confint(model_sd_adj, "log2(glusd)", level = 0.975)
exp(f[1])
exp(f[2])

```


